const puppeteer = require('puppeteer-core');
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
(async () => {
  const browser = await puppeteer.launch({ executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', headless: 'new' });
  const page = await browser.newPage();
  await page.setViewport({ width: 390, height: 844, deviceScaleFactor: 2 });
  await page.goto('http://localhost:8123/ar/', { waitUntil: 'networkidle0' });
  await sleep(2600);
  await page.screenshot({ path: process.argv[2] + '/ar-mobile.png' });
  await page.setViewport({ width: 1440, height: 950, deviceScaleFactor: 1 });
  await page.goto('http://localhost:8123/ar/', { waitUntil: 'networkidle0' });
  await sleep(4400);
  await page.screenshot({ path: process.argv[2] + '/ar-desktop.png' });
  await page.goto('http://localhost:8123/ar/solutions/ecofert/', { waitUntil: 'networkidle0' });
  await page.evaluate(() => document.querySelector('.pyields').scrollIntoView());
  await sleep(600);
  await page.screenshot({ path: process.argv[2] + '/ar-yields.png' });
  await browser.close();
  console.log('ok');
})().catch((e) => { console.error(e.message); process.exit(1); });
